=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Console Application/eMI Spanish Verb Conjugator/Conjugations/Conjugations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="verb">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="form" minOccurs="1" maxOccurs="3">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="infinitive"/>
											<xs:enumeration value="gerund"/>
											<xs:enumeration value="past-participle"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="defective" type="xs:boolean" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="mood" minOccurs="0" maxOccurs="4">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tense" minOccurs="1" maxOccurs="5">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="conjugation" minOccurs="0" maxOccurs="6">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="number" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="singular"/>
																	<xs:enumeration value="plural"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="person" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:unsignedByte">
																	<xs:enumeration value="1"/>
																	<xs:enumeration value="2"/>
																	<xs:enumeration value="3"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="type" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="present"/>
												<xs:enumeration value="imperfect"/>
												<xs:enumeration value="preterite"/>
												<xs:enumeration value="future"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="variant" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="affirmative"/>
												<xs:enumeration value="negative"/>
												<xs:enumeration value="ra"/>
												<xs:enumeration value="se"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="defective" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="indicative"/>
									<xs:enumeration value="subjunctive"/>
									<xs:enumeration value="imperative"/>
									<xs:enumeration value="conditional"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Library/eMI Spanish Verb Conjugator/Conjugations/Irregular/er/perder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">perder</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">pierdo</conjugation>
			<conjugation number="singular" person="2">pierdes</conjugation>
			<conjugation number="singular" person="3">pierde</conjugation>
			<conjugation number="plural" person="3">pierden</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">pierda</conjugation>
			<conjugation number="singular" person="2">pierdas</conjugation>
			<conjugation number="singular" person="3">pierda</conjugation>
			<conjugation number="plural" person="3">pierdan</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">pierde</conjugation>
			<conjugation number="singular" person="3">pierda</conjugation>
			<conjugation number="plural" person="3">pierdan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">pierdas</conjugation>
			<conjugation number="singular" person="3">pierda</conjugation>
			<conjugation number="plural" person="3">pierdan</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Source code/Library/Conjugations/Irregular/er/deshacer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">deshacer</form>
	<form type="past-participle">deshecho</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">deshago</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="1">deshice</conjugation>
			<conjugation number="singular" person="2">deshiciste</conjugation>
			<conjugation number="singular" person="3">deshizo</conjugation>
			<conjugation number="plural" person="1">deshicimos</conjugation>
			<conjugation number="plural" person="2">deshicisteis</conjugation>
			<conjugation number="plural" person="3">deshicieron</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">desharé</conjugation>
			<conjugation number="singular" person="2">desharás</conjugation>
			<conjugation number="singular" person="3">deshará</conjugation>
			<conjugation number="plural" person="1">desharemos</conjugation>
			<conjugation number="plural" person="2">desharéis</conjugation>
			<conjugation number="plural" person="3">desharán</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">deshaga</conjugation>
			<conjugation number="singular" person="2">deshagas</conjugation>
			<conjugation number="singular" person="3">deshaga</conjugation>
			<conjugation number="plural" person="1">deshagamos</conjugation>
			<conjugation number="plural" person="2">deshagáis</conjugation>
			<conjugation number="plural" person="3">deshagan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">deshiciera</conjugation>
			<conjugation number="singular" person="2">deshicieras</conjugation>
			<conjugation number="singular" person="3">deshiciera</conjugation>
			<conjugation number="plural" person="1">deshiciéramos</conjugation>
			<conjugation number="plural" person="2">deshicierais</conjugation>
			<conjugation number="plural" person="3">deshicieran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">deshiciese</conjugation>
			<conjugation number="singular" person="2">deshicieses</conjugation>
			<conjugation number="singular" person="3">deshiciese</conjugation>
			<conjugation number="plural" person="1">deshiciésemos</conjugation>
			<conjugation number="plural" person="2">deshicieseis</conjugation>
			<conjugation number="plural" person="3">deshiciesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">deshiciere</conjugation>
			<conjugation number="singular" person="2">deshicieres</conjugation>
			<conjugation number="singular" person="3">deshiciere</conjugation>
			<conjugation number="plural" person="1">deshiciéremos</conjugation>
			<conjugation number="plural" person="2">deshiciereis</conjugation>
			<conjugation number="plural" person="3">deshicieren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">deshace, deshaz</conjugation>
			<conjugation number="singular" person="3">deshaga</conjugation>
			<conjugation number="plural" person="1">deshagamos</conjugation>
			<conjugation number="plural" person="3">deshagan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">deshagas</conjugation>
			<conjugation number="singular" person="3">deshaga</conjugation>
			<conjugation number="plural" person="1">deshagamos</conjugation>
			<conjugation number="plural" person="2">deshagáis</conjugation>
			<conjugation number="plural" person="3">deshagan</conjugation>
		</tense>
	</mood>
	<mood type="conditional">
		<tense>
			<conjugation number="singular" person="1">desharía</conjugation>
			<conjugation number="singular" person="2">desharías</conjugation>
			<conjugation number="singular" person="3">desharía</conjugation>
			<conjugation number="plural" person="1">desharíamos</conjugation>
			<conjugation number="plural" person="2">desharíais</conjugation>
			<conjugation number="plural" person="3">desharían</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Library/eMI Spanish Verb Conjugator/Conjugations/Irregular/ir/traducir.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">traducir</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">traduzco</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="1">traduje</conjugation>
			<conjugation number="singular" person="2">tradujiste</conjugation>
			<conjugation number="singular" person="3">tradujo</conjugation>
			<conjugation number="plural" person="1">tradujimos</conjugation>
			<conjugation number="plural" person="2">tradujisteis</conjugation>
			<conjugation number="plural" person="3">tradujeron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">traduzca</conjugation>
			<conjugation number="singular" person="2">traduzcas</conjugation>
			<conjugation number="singular" person="3">traduzca</conjugation>
			<conjugation number="plural" person="1">traduzcamos</conjugation>
			<conjugation number="plural" person="2">traduzcáis</conjugation>
			<conjugation number="plural" person="3">traduzcan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">tradujera</conjugation>
			<conjugation number="singular" person="2">tradujeras</conjugation>
			<conjugation number="singular" person="3">tradujera</conjugation>
			<conjugation number="plural" person="1">tradujéramos</conjugation>
			<conjugation number="plural" person="2">tradujerais</conjugation>
			<conjugation number="plural" person="3">tradujeran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">tradujese</conjugation>
			<conjugation number="singular" person="2">tradujeses</conjugation>
			<conjugation number="singular" person="3">tradujese</conjugation>
			<conjugation number="plural" person="1">tradujésemos</conjugation>
			<conjugation number="plural" person="2">tradujeseis</conjugation>
			<conjugation number="plural" person="3">tradujesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">tradujere</conjugation>
			<conjugation number="singular" person="2">tradujeres</conjugation>
			<conjugation number="singular" person="3">tradujere</conjugation>
			<conjugation number="plural" person="1">tradujéremos</conjugation>
			<conjugation number="plural" person="2">tradujereis</conjugation>
			<conjugation number="plural" person="3">tradujeren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="3">traduzca</conjugation>
			<conjugation number="plural" person="1">traduzcamos</conjugation>
			<conjugation number="plural" person="3">traduzcan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">traduzcas</conjugation>
			<conjugation number="singular" person="3">traduzca</conjugation>
			<conjugation number="plural" person="1">traduzcamos</conjugation>
			<conjugation number="plural" person="2">traduzcáis</conjugation>
			<conjugation number="plural" person="3">traduzcan</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Console Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/ir/huir.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">huir</form>
	<form type="gerund">huyendo</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">huyo</conjugation>
			<conjugation number="singular" person="2">huyes</conjugation>
			<conjugation number="singular" person="3">huye</conjugation>
			<conjugation number="plural" person="3">huyen</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="3">huyó</conjugation>
			<conjugation number="plural" person="3">huyeron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">huya</conjugation>
			<conjugation number="singular" person="2">huyas</conjugation>
			<conjugation number="singular" person="3">huya</conjugation>
			<conjugation number="plural" person="1">huyamos</conjugation>
			<conjugation number="plural" person="2">huyáis</conjugation>
			<conjugation number="plural" person="3">huyan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">huyera</conjugation>
			<conjugation number="singular" person="2">huyeras</conjugation>
			<conjugation number="singular" person="3">huyera</conjugation>
			<conjugation number="plural" person="1">huyéramos</conjugation>
			<conjugation number="plural" person="2">huyerais</conjugation>
			<conjugation number="plural" person="3">huyeran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">huyese</conjugation>
			<conjugation number="singular" person="2">huyeses</conjugation>
			<conjugation number="singular" person="3">huyese</conjugation>
			<conjugation number="plural" person="1">huyésemos</conjugation>
			<conjugation number="plural" person="2">huyeseis</conjugation>
			<conjugation number="plural" person="3">huyesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">huyere</conjugation>
			<conjugation number="singular" person="2">huyeres</conjugation>
			<conjugation number="singular" person="3">huyere</conjugation>
			<conjugation number="plural" person="1">huyéremos</conjugation>
			<conjugation number="plural" person="2">huyereis</conjugation>
			<conjugation number="plural" person="3">huyeren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">huye</conjugation>
			<conjugation number="singular" person="3">huya</conjugation>
			<conjugation number="plural" person="1">huyamos</conjugation>
			<conjugation number="plural" person="3">huyan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">huyas</conjugation>
			<conjugation number="singular" person="3">huya</conjugation>
			<conjugation number="plural" person="1">huyamos</conjugation>
			<conjugation number="plural" person="2">huyáis</conjugation>
			<conjugation number="plural" person="3">huyan</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Source code/Library/Conjugations/Irregular/ir/sustituir.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">sustituir</form>
	<form type="gerund">sustituyendo</form>
	<form type="past-participle">sustituido, sustituto</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">sustituyo</conjugation>
			<conjugation number="singular" person="2">sustituyes</conjugation>
			<conjugation number="singular" person="3">sustituye</conjugation>
			<conjugation number="plural" person="3">sustituyen</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="3">sustituyó</conjugation>
			<conjugation number="plural" person="3">sustituyeron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">sustituya</conjugation>
			<conjugation number="singular" person="2">sustituyas</conjugation>
			<conjugation number="singular" person="3">sustituya</conjugation>
			<conjugation number="plural" person="1">sustituyamos</conjugation>
			<conjugation number="plural" person="2">sustituyáis</conjugation>
			<conjugation number="plural" person="3">sustituyan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">sustituyera</conjugation>
			<conjugation number="singular" person="2">sustituyeras</conjugation>
			<conjugation number="singular" person="3">sustituyera</conjugation>
			<conjugation number="plural" person="1">sustituyéramos</conjugation>
			<conjugation number="plural" person="2">sustituyerais</conjugation>
			<conjugation number="plural" person="3">sustituyeran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">sustituyese</conjugation>
			<conjugation number="singular" person="2">sustituyeses</conjugation>
			<conjugation number="singular" person="3">sustituyese</conjugation>
			<conjugation number="plural" person="1">sustituyésemos</conjugation>
			<conjugation number="plural" person="2">sustituyeseis</conjugation>
			<conjugation number="plural" person="3">sustituyesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">sustituyere</conjugation>
			<conjugation number="singular" person="2">sustituyeres</conjugation>
			<conjugation number="singular" person="3">sustituyere</conjugation>
			<conjugation number="plural" person="1">sustituyéremos</conjugation>
			<conjugation number="plural" person="2">sustituyereis</conjugation>
			<conjugation number="plural" person="3">sustituyeren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">sustituye</conjugation>
			<conjugation number="singular" person="3">sustituya</conjugation>
			<conjugation number="plural" person="1">sustituyamos</conjugation>
			<conjugation number="plural" person="3">sustituyan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">sustituyas</conjugation>
			<conjugation number="singular" person="3">sustituya</conjugation>
			<conjugation number="plural" person="1">sustituyamos</conjugation>
			<conjugation number="plural" person="2">sustituyáis</conjugation>
			<conjugation number="plural" person="3">sustituyan</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Windows Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/ar/jugar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">jugar</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">juego</conjugation>
			<conjugation number="singular" person="2">juegas</conjugation>
			<conjugation number="singular" person="3">juega</conjugation>
			<conjugation number="plural" person="3">juegan</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="1">jugué</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">juegue</conjugation>
			<conjugation number="singular" person="2">juegues</conjugation>
			<conjugation number="singular" person="3">juegue</conjugation>
			<conjugation number="plural" person="1">juguemos</conjugation>
			<conjugation number="plural" person="2">juguéis</conjugation>
			<conjugation number="plural" person="3">jueguen</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">juega</conjugation>
			<conjugation number="singular" person="3">juegue</conjugation>
			<conjugation number="plural" person="1">juguemos</conjugation>
			<conjugation number="plural" person="3">jueguen</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">juegues</conjugation>
			<conjugation number="singular" person="3">juegue</conjugation>
			<conjugation number="plural" person="1">juguemos</conjugation>
			<conjugation number="plural" person="2">juguéis</conjugation>
			<conjugation number="plural" person="3">jueguen</conjugation>
		</tense>
	</mood>
</verb>
