=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Console Application/eMI Spanish Verb Conjugator/Conjugations/Conjugations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="verb">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="form" minOccurs="1" maxOccurs="3">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="infinitive"/>
											<xs:enumeration value="gerund"/>
											<xs:enumeration value="past-participle"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="defective" type="xs:boolean" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="mood" minOccurs="0" maxOccurs="4">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tense" minOccurs="1" maxOccurs="5">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="conjugation" minOccurs="0" maxOccurs="6">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="number" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="singular"/>
																	<xs:enumeration value="plural"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="person" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:unsignedByte">
																	<xs:enumeration value="1"/>
																	<xs:enumeration value="2"/>
																	<xs:enumeration value="3"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="type" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="present"/>
												<xs:enumeration value="imperfect"/>
												<xs:enumeration value="preterite"/>
												<xs:enumeration value="future"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="variant" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="affirmative"/>
												<xs:enumeration value="negative"/>
												<xs:enumeration value="ra"/>
												<xs:enumeration value="se"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="defective" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="indicative"/>
									<xs:enumeration value="subjunctive"/>
									<xs:enumeration value="imperative"/>
									<xs:enumeration value="conditional"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Library/eMI Spanish Verb Conjugator/Conjugations/Irregular/er/valer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">valer</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">valgo</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">valdré</conjugation>
			<conjugation number="singular" person="2">valdrás</conjugation>
			<conjugation number="singular" person="3">valdrá</conjugation>
			<conjugation number="plural" person="1">valdremos</conjugation>
			<conjugation number="plural" person="2">valdréis</conjugation>
			<conjugation number="plural" person="3">valdrán</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">valga</conjugation>
			<conjugation number="singular" person="2">valgas</conjugation>
			<conjugation number="singular" person="3">valga</conjugation>
			<conjugation number="plural" person="1">valgamos</conjugation>
			<conjugation number="plural" person="2">valgáis</conjugation>
			<conjugation number="plural" person="3">valgan</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">vale, val</conjugation>
			<conjugation number="singular" person="3">valga</conjugation>
			<conjugation number="plural" person="1">valgamos</conjugation>
			<conjugation number="plural" person="3">valgan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">valgas</conjugation>
			<conjugation number="singular" person="3">valga</conjugation>
			<conjugation number="plural" person="1">valgamos</conjugation>
			<conjugation number="plural" person="2">valgáis</conjugation>
			<conjugation number="plural" person="3">valgan</conjugation>
		</tense>
	</mood>
	<mood type="conditional">
		<tense>
			<conjugation number="singular" person="1">valdría</conjugation>
			<conjugation number="singular" person="2">valdrías</conjugation>
			<conjugation number="singular" person="3">valdría</conjugation>
			<conjugation number="plural" person="1">valdríamos</conjugation>
			<conjugation number="plural" person="2">valdríais</conjugation>
			<conjugation number="plural" person="3">valdrían</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Source code/Library/Conjugations/Irregular/ar/andar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">andar</form>
	<mood type="indicative">
		<tense type="preterite">
			<conjugation number="singular" person="1">anduve</conjugation>
			<conjugation number="singular" person="2">anduviste</conjugation>
			<conjugation number="singular" person="3">anduvo</conjugation>
			<conjugation number="plural" person="1">anduvimos</conjugation>
			<conjugation number="plural" person="2">anduvisteis</conjugation>
			<conjugation number="plural" person="3">anduvieron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">anduviera</conjugation>
			<conjugation number="singular" person="2">anduvieras</conjugation>
			<conjugation number="singular" person="3">anduviera</conjugation>
			<conjugation number="plural" person="1">anduviéramos</conjugation>
			<conjugation number="plural" person="2">anduvierais</conjugation>
			<conjugation number="plural" person="3">anduvieran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">anduviese</conjugation>
			<conjugation number="singular" person="2">anduvieses</conjugation>
			<conjugation number="singular" person="3">anduviese</conjugation>
			<conjugation number="plural" person="1">anduviésemos</conjugation>
			<conjugation number="plural" person="2">anduvieseis</conjugation>
			<conjugation number="plural" person="3">anduviesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">anduviere</conjugation>
			<conjugation number="singular" person="2">anduvieres</conjugation>
			<conjugation number="singular" person="3">anduviere</conjugation>
			<conjugation number="plural" person="1">anduviéremos</conjugation>
			<conjugation number="plural" person="2">anduviereis</conjugation>
			<conjugation number="plural" person="3">anduvieren</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Console Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/er/proponer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">proponer</form>
	<form type="past-participle">propuesto</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">propongo</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="1">propuse</conjugation>
			<conjugation number="singular" person="2">propusiste</conjugation>
			<conjugation number="singular" person="3">propuso</conjugation>
			<conjugation number="plural" person="1">propusimos</conjugation>
			<conjugation number="plural" person="2">propusisteis</conjugation>
			<conjugation number="plural" person="3">propusieron</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">propondré</conjugation>
			<conjugation number="singular" person="2">propondrás</conjugation>
			<conjugation number="singular" person="3">propondrá</conjugation>
			<conjugation number="plural" person="1">propondremos</conjugation>
			<conjugation number="plural" person="2">propondréis</conjugation>
			<conjugation number="plural" person="3">propondrán</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">proponga</conjugation>
			<conjugation number="singular" person="2">propongas</conjugation>
			<conjugation number="singular" person="3">proponga</conjugation>
			<conjugation number="plural" person="1">propongamos</conjugation>
			<conjugation number="plural" person="2">propongáis</conjugation>
			<conjugation number="plural" person="3">propongan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">propusiera</conjugation>
			<conjugation number="singular" person="2">propusieras</conjugation>
			<conjugation number="singular" person="3">propusiera</conjugation>
			<conjugation number="plural" person="1">propusiéramos</conjugation>
			<conjugation number="plural" person="2">propusierais</conjugation>
			<conjugation number="plural" person="3">propusieran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">propusiese</conjugation>
			<conjugation number="singular" person="2">propusieses</conjugation>
			<conjugation number="singular" person="3">propusiese</conjugation>
			<conjugation number="plural" person="1">propusiésemos</conjugation>
			<conjugation number="plural" person="2">propusieseis</conjugation>
			<conjugation number="plural" person="3">propusiesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">propusiere</conjugation>
			<conjugation number="singular" person="2">propusieres</conjugation>
			<conjugation number="singular" person="3">propusiere</conjugation>
			<conjugation number="plural" person="1">propusiéremos</conjugation>
			<conjugation number="plural" person="2">propusiereis</conjugation>
			<conjugation number="plural" person="3">propusieren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">propón</conjugation>
			<conjugation number="singular" person="3">proponga</conjugation>
			<conjugation number="plural" person="1">propongamos</conjugation>
			<conjugation number="plural" person="3">propongan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">propongas</conjugation>
			<conjugation number="singular" person="3">proponga</conjugation>
			<conjugation number="plural" person="1">propongamos</conjugation>
			<conjugation number="plural" person="2">propongáis</conjugation>
			<conjugation number="plural" person="3">propongan</conjugation>
		</tense>
	</mood>
	<mood type="conditional">
		<tense>
			<conjugation number="singular" person="1">propondría</conjugation>
			<conjugation number="singular" person="2">propondrías</conjugation>
			<conjugation number="singular" person="3">propondría</conjugation>
			<conjugation number="plural" person="1">propondríamos</conjugation>
			<conjugation number="plural" person="2">propondríais</conjugation>
			<conjugation number="plural" person="3">propondrían</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Source code/Library/Conjugations/Irregular/ir/construir.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">construir</form>
	<form type="gerund">construyendo</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">construyo</conjugation>
			<conjugation number="singular" person="2">construyes</conjugation>
			<conjugation number="singular" person="3">construye</conjugation>
			<conjugation number="plural" person="3">construyen</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="3">construyó</conjugation>
			<conjugation number="plural" person="3">construyeron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">construya</conjugation>
			<conjugation number="singular" person="2">construyas</conjugation>
			<conjugation number="singular" person="3">construya</conjugation>
			<conjugation number="plural" person="1">construyamos</conjugation>
			<conjugation number="plural" person="2">construyáis</conjugation>
			<conjugation number="plural" person="3">construyan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">construyera</conjugation>
			<conjugation number="singular" person="2">construyeras</conjugation>
			<conjugation number="singular" person="3">construyera</conjugation>
			<conjugation number="plural" person="1">construyéramos</conjugation>
			<conjugation number="plural" person="2">construyerais</conjugation>
			<conjugation number="plural" person="3">construyeran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">construyese</conjugation>
			<conjugation number="singular" person="2">construyeses</conjugation>
			<conjugation number="singular" person="3">construyese</conjugation>
			<conjugation number="plural" person="1">construyésemos</conjugation>
			<conjugation number="plural" person="2">construyeseis</conjugation>
			<conjugation number="plural" person="3">construyesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">construyere</conjugation>
			<conjugation number="singular" person="2">construyeres</conjugation>
			<conjugation number="singular" person="3">construyere</conjugation>
			<conjugation number="plural" person="1">construyéremos</conjugation>
			<conjugation number="plural" person="2">construyereis</conjugation>
			<conjugation number="plural" person="3">construyeren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">construye</conjugation>
			<conjugation number="singular" person="3">construya</conjugation>
			<conjugation number="plural" person="1">construyamos</conjugation>
			<conjugation number="plural" person="3">construyan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">construyas</conjugation>
			<conjugation number="singular" person="3">construya</conjugation>
			<conjugation number="plural" person="1">construyamos</conjugation>
			<conjugation number="plural" person="2">construyáis</conjugation>
			<conjugation number="plural" person="3">construyan</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Windows Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/ar/estar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">estar</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">estoy</conjugation>
			<conjugation number="singular" person="2">estás</conjugation>
			<conjugation number="singular" person="3">está</conjugation>
			<conjugation number="plural" person="3">están</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="1">estuve</conjugation>
			<conjugation number="singular" person="2">estuviste</conjugation>
			<conjugation number="singular" person="3">estuvo</conjugation>
			<conjugation number="plural" person="1">estuvimos</conjugation>
			<conjugation number="plural" person="2">estuvisteis</conjugation>
			<conjugation number="plural" person="3">estuvieron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">esté</conjugation>
			<conjugation number="singular" person="2">estés</conjugation>
			<conjugation number="singular" person="3">esté</conjugation>
			<conjugation number="plural" person="3">estén</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">estuviera</conjugation>
			<conjugation number="singular" person="2">estuvieras</conjugation>
			<conjugation number="singular" person="3">estuviera</conjugation>
			<conjugation number="plural" person="1">estuviéramos</conjugation>
			<conjugation number="plural" person="2">estuvierais</conjugation>
			<conjugation number="plural" person="3">estuvieran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">estuviese</conjugation>
			<conjugation number="singular" person="2">estuvieses</conjugation>
			<conjugation number="singular" person="3">estuviese</conjugation>
			<conjugation number="plural" person="1">estuviésemos</conjugation>
			<conjugation number="plural" person="2">estuvieseis</conjugation>
			<conjugation number="plural" person="3">estuviesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">estuviere</conjugation>
			<conjugation number="singular" person="2">estuvieres</conjugation>
			<conjugation number="singular" person="3">estuviere</conjugation>
			<conjugation number="plural" person="1">estuviéremos</conjugation>
			<conjugation number="plural" person="2">estuviereis</conjugation>
			<conjugation number="plural" person="3">estuvieren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">está</conjugation>
			<conjugation number="singular" person="3">esté</conjugation>
			<conjugation number="plural" person="3">estén</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">estés</conjugation>
			<conjugation number="singular" person="3">esté</conjugation>
			<conjugation number="plural" person="3">estén</conjugation>
		</tense>
	</mood>
	<mood type="conditional">
		<tense>
			<conjugation number="singular" person="1">estaría</conjugation>
			<conjugation number="singular" person="2">estarías</conjugation>
			<conjugation number="singular" person="3">estaría</conjugation>
			<conjugation number="plural" person="1">estaríamos</conjugation>
			<conjugation number="plural" person="2">estaríais</conjugation>
			<conjugation number="plural" person="3">estarían</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Windows Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/er/entender.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">entender</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">entiendo</conjugation>
			<conjugation number="singular" person="2">entiendes</conjugation>
			<conjugation number="singular" person="3">entiende</conjugation>
			<conjugation number="plural" person="3">entienden</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">entienda</conjugation>
			<conjugation number="singular" person="2">entiendas</conjugation>
			<conjugation number="singular" person="3">entienda</conjugation>
			<conjugation number="plural" person="3">entiendan</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">entiende</conjugation>
			<conjugation number="singular" person="3">entienda</conjugation>
			<conjugation number="plural" person="3">entiendan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">entiendas</conjugation>
			<conjugation number="singular" person="3">entienda</conjugation>
			<conjugation number="plural" person="3">entiendan</conjugation>
		</tense>
	</mood>
</verb>
