=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Console Application/eMI Spanish Verb Conjugator/Conjugations/Conjugations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="verb">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="form" minOccurs="1" maxOccurs="3">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="infinitive"/>
											<xs:enumeration value="gerund"/>
											<xs:enumeration value="past-participle"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="defective" type="xs:boolean" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="mood" minOccurs="0" maxOccurs="4">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tense" minOccurs="1" maxOccurs="5">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="conjugation" minOccurs="0" maxOccurs="6">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="number" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="singular"/>
																	<xs:enumeration value="plural"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="person" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:unsignedByte">
																	<xs:enumeration value="1"/>
																	<xs:enumeration value="2"/>
																	<xs:enumeration value="3"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="type" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="present"/>
												<xs:enumeration value="imperfect"/>
												<xs:enumeration value="preterite"/>
												<xs:enumeration value="future"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="variant" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="affirmative"/>
												<xs:enumeration value="negative"/>
												<xs:enumeration value="ra"/>
												<xs:enumeration value="se"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="defective" type="xs:boolean" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="indicative"/>
									<xs:enumeration value="subjunctive"/>
									<xs:enumeration value="imperative"/>
									<xs:enumeration value="conditional"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Console Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/ar/replicar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">replicar</form>
	<mood type="indicative">
		<tense type="preterite">
			<conjugation number="singular" person="1">repliqué</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">replique</conjugation>
			<conjugation number="singular" person="2">repliques</conjugation>
			<conjugation number="singular" person="3">replique</conjugation>
			<conjugation number="plural" person="1">repliquemos</conjugation>
			<conjugation number="plural" person="2">repliquéis</conjugation>
			<conjugation number="plural" person="3">repliquen</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="3">replique</conjugation>
			<conjugation number="plural" person="1">repliquemos</conjugation>
			<conjugation number="plural" person="3">repliquen</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">repliques</conjugation>
			<conjugation number="singular" person="3">replique</conjugation>
			<conjugation number="plural" person="1">repliquemos</conjugation>
			<conjugation number="plural" person="2">repliquéis</conjugation>
			<conjugation number="plural" person="3">repliquen</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Console Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/er/saber.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">saber</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">sé</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="1">supe</conjugation>
			<conjugation number="singular" person="2">supiste</conjugation>
			<conjugation number="singular" person="3">supo</conjugation>
			<conjugation number="plural" person="1">supimos</conjugation>
			<conjugation number="plural" person="2">supisteis</conjugation>
			<conjugation number="plural" person="3">supieron</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">sabré</conjugation>
			<conjugation number="singular" person="2">sabrás</conjugation>
			<conjugation number="singular" person="3">sabrá</conjugation>
			<conjugation number="plural" person="1">sabremos</conjugation>
			<conjugation number="plural" person="2">sabréis</conjugation>
			<conjugation number="plural" person="3">sabrán</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">sepa</conjugation>
			<conjugation number="singular" person="2">sepas</conjugation>
			<conjugation number="singular" person="3">sepa</conjugation>
			<conjugation number="plural" person="1">sepamos</conjugation>
			<conjugation number="plural" person="2">sepáis</conjugation>
			<conjugation number="plural" person="3">sepan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">supiera</conjugation>
			<conjugation number="singular" person="2">supieras</conjugation>
			<conjugation number="singular" person="3">supiera</conjugation>
			<conjugation number="plural" person="1">supiéramos</conjugation>
			<conjugation number="plural" person="2">supierais</conjugation>
			<conjugation number="plural" person="3">supieran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">supiese</conjugation>
			<conjugation number="singular" person="2">supieses</conjugation>
			<conjugation number="singular" person="3">supiese</conjugation>
			<conjugation number="plural" person="1">supiésemos</conjugation>
			<conjugation number="plural" person="2">supieseis</conjugation>
			<conjugation number="plural" person="3">supiesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">supiere</conjugation>
			<conjugation number="singular" person="2">supieres</conjugation>
			<conjugation number="singular" person="3">supiere</conjugation>
			<conjugation number="plural" person="1">supiéremos</conjugation>
			<conjugation number="plural" person="2">supiereis</conjugation>
			<conjugation number="plural" person="3">supieren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="3">sepa</conjugation>
			<conjugation number="plural" person="1">sepamos</conjugation>
			<conjugation number="plural" person="3">sepan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">sepas</conjugation>
			<conjugation number="singular" person="3">sepa</conjugation>
			<conjugation number="plural" person="1">sepamos</conjugation>
			<conjugation number="plural" person="2">sepáis</conjugation>
			<conjugation number="plural" person="3">sepan</conjugation>
		</tense>
	</mood>
	<mood type="conditional">
		<tense>
			<conjugation number="singular" person="1">sabría</conjugation>
			<conjugation number="singular" person="2">sabrías</conjugation>
			<conjugation number="singular" person="3">sabría</conjugation>
			<conjugation number="plural" person="1">sabríamos</conjugation>
			<conjugation number="plural" person="2">sabríais</conjugation>
			<conjugation number="plural" person="3">sabrían</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Windows Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/ir/pedir.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">pedir</form>
	<form type="gerund">pidiendo</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">pido</conjugation>
			<conjugation number="singular" person="2">pides</conjugation>
			<conjugation number="singular" person="3">pide</conjugation>
			<conjugation number="plural" person="3">piden</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="3">pidió</conjugation>
			<conjugation number="plural" person="3">pidieron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">pida</conjugation>
			<conjugation number="singular" person="2">pidas</conjugation>
			<conjugation number="singular" person="3">pida</conjugation>
			<conjugation number="plural" person="1">pidamos</conjugation>
			<conjugation number="plural" person="2">pidáis</conjugation>
			<conjugation number="plural" person="3">pidan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">pidiera</conjugation>
			<conjugation number="singular" person="2">pidieras</conjugation>
			<conjugation number="singular" person="3">pidiera</conjugation>
			<conjugation number="plural" person="1">pidiéramos</conjugation>
			<conjugation number="plural" person="2">pidierais</conjugation>
			<conjugation number="plural" person="3">pidieran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">pidiese</conjugation>
			<conjugation number="singular" person="2">pidieses</conjugation>
			<conjugation number="singular" person="3">pidiese</conjugation>
			<conjugation number="plural" person="1">pidiésemos</conjugation>
			<conjugation number="plural" person="2">pidieseis</conjugation>
			<conjugation number="plural" person="3">pidiesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">pidiere</conjugation>
			<conjugation number="singular" person="2">pidieres</conjugation>
			<conjugation number="singular" person="3">pidiere</conjugation>
			<conjugation number="plural" person="1">pidiéremos</conjugation>
			<conjugation number="plural" person="2">pidiereis</conjugation>
			<conjugation number="plural" person="3">pidieren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">pide</conjugation>
			<conjugation number="singular" person="3">pida</conjugation>
			<conjugation number="plural" person="1">pidamos</conjugation>
			<conjugation number="plural" person="3">pidan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">pidas</conjugation>
			<conjugation number="singular" person="3">pida</conjugation>
			<conjugation number="plural" person="1">pidamos</conjugation>
			<conjugation number="plural" person="2">pidáis</conjugation>
			<conjugation number="plural" person="3">pidan</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Library/eMI Spanish Verb Conjugator/Conjugations/Irregular/ir/consentir.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">consentir</form>
	<form type="gerund">consintiendo</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">consiento</conjugation>
			<conjugation number="singular" person="2">consientes</conjugation>
			<conjugation number="singular" person="3">consiente</conjugation>
			<conjugation number="plural" person="3">consienten</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="3">consintió</conjugation>
			<conjugation number="plural" person="3">consintieron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">consienta</conjugation>
			<conjugation number="singular" person="2">consientas</conjugation>
			<conjugation number="singular" person="3">consienta</conjugation>
			<conjugation number="plural" person="1">consintamos</conjugation>
			<conjugation number="plural" person="2">consintáis</conjugation>
			<conjugation number="plural" person="3">consientan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">consintiera</conjugation>
			<conjugation number="singular" person="2">consintieras</conjugation>
			<conjugation number="singular" person="3">consintiera</conjugation>
			<conjugation number="plural" person="1">consintiéramos</conjugation>
			<conjugation number="plural" person="2">consintierais</conjugation>
			<conjugation number="plural" person="3">consintieran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">consintiese</conjugation>
			<conjugation number="singular" person="2">consintieses</conjugation>
			<conjugation number="singular" person="3">consintiese</conjugation>
			<conjugation number="plural" person="1">consintiésemos</conjugation>
			<conjugation number="plural" person="2">consintieseis</conjugation>
			<conjugation number="plural" person="3">consintiesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">consintiere</conjugation>
			<conjugation number="singular" person="2">consintieres</conjugation>
			<conjugation number="singular" person="3">consintiere</conjugation>
			<conjugation number="plural" person="1">consintiéremos</conjugation>
			<conjugation number="plural" person="2">consintiereis</conjugation>
			<conjugation number="plural" person="3">consintieren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">consiente</conjugation>
			<conjugation number="singular" person="3">consienta</conjugation>
			<conjugation number="plural" person="1">consintamos</conjugation>
			<conjugation number="plural" person="3">consientan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">consientas</conjugation>
			<conjugation number="singular" person="3">consienta</conjugation>
			<conjugation number="plural" person="1">consintamos</conjugation>
			<conjugation number="plural" person="2">consintáis</conjugation>
			<conjugation number="plural" person="3">consientan</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Windows Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/er/exponer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">exponer</form>
	<form type="past-participle">expuesto</form>
	<mood type="indicative">
		<tense type="present">
			<conjugation number="singular" person="1">expongo</conjugation>
		</tense>
		<tense type="preterite">
			<conjugation number="singular" person="1">expuse</conjugation>
			<conjugation number="singular" person="2">expusiste</conjugation>
			<conjugation number="singular" person="3">expuso</conjugation>
			<conjugation number="plural" person="1">expusimos</conjugation>
			<conjugation number="plural" person="2">expusisteis</conjugation>
			<conjugation number="plural" person="3">expusieron</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">expondré</conjugation>
			<conjugation number="singular" person="2">expondrás</conjugation>
			<conjugation number="singular" person="3">expondrá</conjugation>
			<conjugation number="plural" person="1">expondremos</conjugation>
			<conjugation number="plural" person="2">expondréis</conjugation>
			<conjugation number="plural" person="3">expondrán</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="present">
			<conjugation number="singular" person="1">exponga</conjugation>
			<conjugation number="singular" person="2">expongas</conjugation>
			<conjugation number="singular" person="3">exponga</conjugation>
			<conjugation number="plural" person="1">expongamos</conjugation>
			<conjugation number="plural" person="2">expongáis</conjugation>
			<conjugation number="plural" person="3">expongan</conjugation>
		</tense>
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">expusiera</conjugation>
			<conjugation number="singular" person="2">expusieras</conjugation>
			<conjugation number="singular" person="3">expusiera</conjugation>
			<conjugation number="plural" person="1">expusiéramos</conjugation>
			<conjugation number="plural" person="2">expusierais</conjugation>
			<conjugation number="plural" person="3">expusieran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">expusiese</conjugation>
			<conjugation number="singular" person="2">expusieses</conjugation>
			<conjugation number="singular" person="3">expusiese</conjugation>
			<conjugation number="plural" person="1">expusiésemos</conjugation>
			<conjugation number="plural" person="2">expusieseis</conjugation>
			<conjugation number="plural" person="3">expusiesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">expusiere</conjugation>
			<conjugation number="singular" person="2">expusieres</conjugation>
			<conjugation number="singular" person="3">expusiere</conjugation>
			<conjugation number="plural" person="1">expusiéremos</conjugation>
			<conjugation number="plural" person="2">expusiereis</conjugation>
			<conjugation number="plural" person="3">expusieren</conjugation>
		</tense>
	</mood>
	<mood type="imperative">
		<tense variant="affirmative">
			<conjugation number="singular" person="2">expón</conjugation>
			<conjugation number="singular" person="3">exponga</conjugation>
			<conjugation number="plural" person="1">expongamos</conjugation>
			<conjugation number="plural" person="3">expongan</conjugation>
		</tense>
		<tense variant="negative">
			<conjugation number="singular" person="2">expongas</conjugation>
			<conjugation number="singular" person="3">exponga</conjugation>
			<conjugation number="plural" person="1">expongamos</conjugation>
			<conjugation number="plural" person="2">expongáis</conjugation>
			<conjugation number="plural" person="3">expongan</conjugation>
		</tense>
	</mood>
	<mood type="conditional">
		<tense>
			<conjugation number="singular" person="1">expondría</conjugation>
			<conjugation number="singular" person="2">expondrías</conjugation>
			<conjugation number="singular" person="3">expondría</conjugation>
			<conjugation number="plural" person="1">expondríamos</conjugation>
			<conjugation number="plural" person="2">expondríais</conjugation>
			<conjugation number="plural" person="3">expondrían</conjugation>
		</tense>
	</mood>
</verb>

=== eMedia-Intellect/eMI-Spanish-Verb-Conjugator/Software build/Console Application/eMI Spanish Verb Conjugator/Conjugations/Irregular/er/creer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright © 2019 eMedia Intellect.

This file is part of eMI Spanish Verb Conjugator.

eMI Spanish Verb Conjugator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

eMI Spanish Verb Conjugator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with eMI Spanish Verb Conjugator. If not, see http://www.gnu.org/licenses/.
-->
<verb xmlns="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://emi.is/eMI-Spanish-Verb-Conjugator/Conjugations ../../Conjugations.xsd">
	<form type="infinitive">creer</form>
	<mood type="indicative">
		<tense type="preterite">
			<conjugation number="singular" person="2">creíste</conjugation>
			<conjugation number="singular" person="3">creyó</conjugation>
			<conjugation number="plural" person="1">creímos</conjugation>
			<conjugation number="plural" person="2">creísteis</conjugation>
			<conjugation number="plural" person="3">creyeron</conjugation>
		</tense>
	</mood>
	<mood type="subjunctive">
		<tense type="imperfect" variant="ra">
			<conjugation number="singular" person="1">creyera</conjugation>
			<conjugation number="singular" person="2">creyeras</conjugation>
			<conjugation number="singular" person="3">creyera</conjugation>
			<conjugation number="plural" person="1">creyéramos</conjugation>
			<conjugation number="plural" person="2">creyerais</conjugation>
			<conjugation number="plural" person="3">creyeran</conjugation>
		</tense>
		<tense type="imperfect" variant="se">
			<conjugation number="singular" person="1">creyese</conjugation>
			<conjugation number="singular" person="2">creyeses</conjugation>
			<conjugation number="singular" person="3">creyese</conjugation>
			<conjugation number="plural" person="1">creyésemos</conjugation>
			<conjugation number="plural" person="2">creyeseis</conjugation>
			<conjugation number="plural" person="3">creyesen</conjugation>
		</tense>
		<tense type="future">
			<conjugation number="singular" person="1">creyere</conjugation>
			<conjugation number="singular" person="2">creyeres</conjugation>
			<conjugation number="singular" person="3">creyere</conjugation>
			<conjugation number="plural" person="1">creyéremos</conjugation>
			<conjugation number="plural" person="2">creyereis</conjugation>
			<conjugation number="plural" person="3">creyeren</conjugation>
		</tense>
	</mood>
</verb>
